### ISSUE TITLE
Multiple sensors?

### ISSUE THREAD

**Issue by xoferz** [jpulakka/nordpool_diff#27]
Is it possible to create multiple sensors with different parameters?

**Comment by jpulakka** [comment]
Yes it is, as mentioned in https://github.com/jpulakka/nordpool_diff#filter-type-triangle-and-rectangle

> You can set up several nordpool_diff entities, each with different parameters

So just add several entities such as 

```
sensor:
  - platform: nordpool_diff
    filter_length: 10
  - platform: nordpool_diff
    filter_length: 15
  - platform: nordpool_diff
    filter_length: 10
    filter_type: triangle
    normalize: max_min_sqrt_max
    etc.
```
